CREATE TABLE IF NOT EXISTS properties (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  price VARCHAR(100) NOT NULL,
  type ENUM('Land', 'House', 'Apartment') NOT NULL,
  image VARCHAR(512) NOT NULL,
  beds INT DEFAULT NULL,
  baths INT DEFAULT NULL,
  sqft INT DEFAULT NULL,
  featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS floor_plans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  property_id INT NOT NULL,
  label VARCHAR(255) NOT NULL,
  image VARCHAR(512) NOT NULL,
  FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  image VARCHAR(512) NOT NULL,
  description TEXT NOT NULL,
  location VARCHAR(255) DEFAULT NULL,
  year VARCHAR(4) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
